var colors = [
    {
      "id": -1,
      "is_trans": false,
      "name": "Any",
      "rgb": "000000",
      "value": -1,
      "label": "Any",
    },
    {
        "id": 0,
        "is_trans": false,
        "name": "Black",
        "rgb": "05131D",
        "value": 0,
        "label": "Black",
      },
      {
        "id": 1,
        "is_trans": false,
        "name": "Blue",
        "rgb": "0055BF",
        "value": 1,
        "label": "Blue",
      },
      {
        "id": 2,
        "is_trans": false,
        "name": "Green",
        "rgb": "237841",
        "value": 2,
        "label": "Green",
      },
      {
        "id": 3,
        "is_trans": false,
        "name": "Dark Turquoise",
        "rgb": "008F9B",
        "value": 3,
        "label": "Dark Turquoise",
      },
      {
        "id": 4,
        "is_trans": false,
        "name": "Red",
        "rgb": "C91A09",
        "value": 4,
        "label": "Red",
      },
      {
        "id": 5,
        "is_trans": false,
        "name": "Dark Pink",
        "rgb": "C870A0",
        "value": 5,
        "label": "Dark Pink",
      },
      {
        "id": 6,
        "is_trans": false,
        "name": "Brown",
        "rgb": "583927",
        "value": 6,
        "label": "Brown",
      },
      {
        "id": 7,
        "is_trans": false,
        "name": "Light Gray",
        "rgb": "9BA19D",
        "value": 7,
        "label": "Light Gray",
      },
      {
        "id": 8,
        "is_trans": false,
        "name": "Dark Gray",
        "rgb": "6D6E5C",
        "value": 8,
        "label": "Dark Gray",
      },
      {
        "id": 9,
        "is_trans": false,
        "name": "Light Blue",
        "rgb": "B4D2E3",
        "value": 9,
        "label": "Light Blue",
      },
      {
        "id": 10,
        "is_trans": false,
        "name": "Bright Green",
        "rgb": "4B9F4A",
        "value": 10,
        "label": "Bright Green",
      },
      {
        "id": 11,
        "is_trans": false,
        "name": "Light Turquoise",
        "rgb": "55A5AF",
        "value": 11,
        "label": "Light Turquoise",
      },
      {
        "id": 12,
        "is_trans": false,
        "name": "Salmon",
        "rgb": "F2705E",
        "value": 12,
        "label": "Salmon",
      },
      {
        "id": 13,
        "is_trans": false,
        "name": "Pink",
        "rgb": "FC97AC",
        "value": 13,
        "label": "Pink",
      },
      {
        "id": 14,
        "is_trans": false,
        "name": "Yellow",
        "rgb": "F2CD37",
        "value": 14,
        "label": "Yellow",
      },
      {
        "id": 15,
        "is_trans": false,
        "name": "White",
        "rgb": "FFFFFF",
        "value": 15,
        "label": "White",
      },
      {
        "id": 17,
        "is_trans": false,
        "name": "Light Green",
        "rgb": "C2DAB8",
        "value": 17,
        "label": "Light Green",
      },
      {
        "id": 18,
        "is_trans": false,
        "name": "Light Yellow",
        "rgb": "FBE696",
        "value": 18,
        "label": "Light Yellow",
      },
      {
        "id": 19,
        "is_trans": false,
        "name": "Tan",
        "rgb": "E4CD9E",
        "value": 19,
        "label": "Tan",
      },
      {
        "id": 20,
        "is_trans": false,
        "name": "Light Violet",
        "rgb": "C9CAE2",
        "value": 20,
        "label": "Light Violet",
      },
      {
        "id": 21,
        "is_trans": false,
        "name": "Glow In Dark Opaque",
        "rgb": "D4D5C9",
        "value": 21,
        "label": "Glow In Dark Opaque",
      },
      {
        "id": 22,
        "is_trans": false,
        "name": "Purple",
        "rgb": "81007B",
        "value": 22,
        "label": "Purple",
      },
      {
        "id": 23,
        "is_trans": false,
        "name": "Dark Blue-Violet",
        "rgb": "2032B0",
        "value": 23,
        "label": "Dark Blue-Violet",
      },
      {
        "id": 25,
        "is_trans": false,
        "name": "Orange",
        "rgb": "FE8A18",
        "value": 25,
        "label": "Orange",
      },
      {
        "id": 26,
        "is_trans": false,
        "name": "Magenta",
        "rgb": "923978",
        "value": 26,
        "label": "Magenta",
      },
      {
        "id": 27,
        "is_trans": false,
        "name": "Lime",
        "rgb": "BBE90B",
        "value": 27,
        "label": "Lime",
      },
      {
        "id": 28,
        "is_trans": false,
        "name": "Dark Tan",
        "rgb": "958A73",
        "value": 28,
        "label": "Dark Tan",
      },
      {
        "id": 29,
        "is_trans": false,
        "name": "Bright Pink",
        "rgb": "E4ADC8",
        "value": 29,
        "label": "Bright Pink",
      },
      {
        "id": 30,
        "is_trans": false,
        "name": "Medium Lavender",
        "rgb": "AC78BA",
        "value": 30,
        "label": "Medium Lavender",
      },
      {
        "id": 31,
        "is_trans": false,
        "name": "Lavender",
        "rgb": "E1D5ED",
        "value": 31,
        "label": "Lavender",
      },
      {
        "id": 32,
        "is_trans": true,
        "name": "Trans-Black IR Lens",
        "rgb": "635F52",
        "value": 32,
        "label": "Trans-Black IR Lens",
      },
      {
        "id": 33,
        "is_trans": true,
        "name": "Trans-Dark Blue",
        "rgb": "0020A0",
        "value": 33,
        "label": "Trans-Dark Blue",
      },
      {
        "id": 34,
        "is_trans": true,
        "name": "Trans-Green",
        "rgb": "84B68D",
        "value": 34,
        "label": "Trans-Green",
      },
      {
        "id": 35,
        "is_trans": true,
        "name": "Trans-Bright Green",
        "rgb": "D9E4A7",
        "value": 35,
        "label": "Trans-Bright Green",
      },
      {
        "id": 36,
        "is_trans": true,
        "name": "Trans-Red",
        "rgb": "C91A09",
        "value": 36,
        "label": "Trans-Red",
      },
      {
        "id": 40,
        "is_trans": true,
        "name": "Trans-Brown",
        "rgb": "635F52",
        "value": 40,
        "label": "Trans-Brown",
      },
      {
        "id": 41,
        "is_trans": true,
        "name": "Trans-Light Blue",
        "rgb": "AEEFEC",
        "value": 41,
        "label": "Trans-Light Blue",
      },
      {
        "id": 42,
        "is_trans": true,
        "name": "Trans-Neon Green",
        "rgb": "F8F184",
        "value": 42,
        "label": "Trans-Neon Green",
      },
      {
        "id": 43,
        "is_trans": true,
        "name": "Trans-Very Lt Blue",
        "rgb": "C1DFF0",
        "value": 43,
        "label": "Trans-Very Lt Blue",
      },
      {
        "id": 45,
        "is_trans": true,
        "name": "Trans-Dark Pink",
        "rgb": "DF6695",
        "value": 45,
        "label": "Trans-Dark Pink",
      },
      {
        "id": 46,
        "is_trans": true,
        "name": "Trans-Yellow",
        "rgb": "F5CD2F",
        "value": 46,
        "label": "Trans-Yellow",
      },
      {
        "id": 47,
        "is_trans": true,
        "name": "Trans-Clear",
        "rgb": "FCFCFC",
        "value": 47,
        "label": "Trans-Clear",
      },
      {
        "id": 52,
        "is_trans": true,
        "name": "Trans-Purple",
        "rgb": "A5A5CB",
        "value": 52,
        "label": "Trans-Purple",
      },
      {
        "id": 54,
        "is_trans": true,
        "name": "Trans-Neon Yellow",
        "rgb": "DAB000",
        "value": 54,
        "label": "Trans-Neon Yellow",
      },
      {
        "id": 57,
        "is_trans": true,
        "name": "Trans-Neon Orange",
        "rgb": "FF800D",
        "value": 57,
        "label": "Trans-Neon Orange",
      },
      {
        "id": 60,
        "is_trans": false,
        "name": "Chrome Antique Brass",
        "rgb": "645A4C",
        "value": 60,
        "label": "Chrome Antique Brass",
      },
      {
        "id": 61,
        "is_trans": false,
        "name": "Chrome Blue",
        "rgb": "6C96BF",
        "value": 61,
        "label": "Chrome Blue",
      },
      {
        "id": 62,
        "is_trans": false,
        "name": "Chrome Green",
        "rgb": "3CB371",
        "value": 62,
        "label": "Chrome Green",
      },
      {
        "id": 63,
        "is_trans": false,
        "name": "Chrome Pink",
        "rgb": "AA4D8E",
        "value": 63,
        "label": "Chrome Pink",
      },
      {
        "id": 64,
        "is_trans": false,
        "name": "Chrome Black",
        "rgb": "1B2A34",
        "value": 64,
        "label": "Chrome Black",
      },
      {
        "id": 68,
        "is_trans": false,
        "name": "Very Light Orange",
        "rgb": "F3CF9B",
        "value": 68,
        "label": "Very Light Orange",
      },
      {
        "id": 69,
        "is_trans": false,
        "name": "Light Purple",
        "rgb": "CD6298",
        "value": 69,
        "label": "Light Purple",
      },
      {
        "id": 70,
        "is_trans": false,
        "name": "Reddish Brown",
        "rgb": "582A12",
        "value": 70,
        "label": "Reddish Brown",
      },
      {
        "id": 71,
        "is_trans": false,
        "name": "Light Bluish Gray",
        "rgb": "A0A5A9",
        "value": 71,
        "label": "Light Bluish Gray",
      },
      {
        "id": 72,
        "is_trans": false,
        "name": "Dark Bluish Gray",
        "rgb": "6C6E68",
        "value": 72,
        "label": "Dark Bluish Gray",
      },
      {
        "id": 73,
        "is_trans": false,
        "name": "Medium Blue",
        "rgb": "5A93DB",
        "value": 73,
        "label": "Medium Blue",
      },
      {
        "id": 74,
        "is_trans": false,
        "name": "Medium Green",
        "rgb": "73DCA1",
        "value": 74,
        "label": "Medium Green",
      },
      {
        "id": 75,
        "is_trans": false,
        "name": "Speckle Black-Copper",
        "rgb": "05131D",
        "value": 75,
        "label": "Speckle Black-Copper",
      },
      {
        "id": 76,
        "is_trans": false,
        "name": "Speckle DBGray-Silver",
        "rgb": "6C6E68",
        "value": 76,
        "label": "Speckle DBGray-Silver",
      },
      {
        "id": 77,
        "is_trans": false,
        "name": "Light Pink",
        "rgb": "FECCCF",
        "value": 77,
        "label": "Light Pink",
      },
      {
        "id": 78,
        "is_trans": false,
        "name": "Light Nougat",
        "rgb": "F6D7B3",
        "value": 78,
        "label": "Light Nougat",
      },
      {
        "id": 79,
        "is_trans": false,
        "name": "Milky White",
        "rgb": "FFFFFF",
        "value": 79,
        "label": "Milky White",
      },
      {
        "id": 80,
        "is_trans": false,
        "name": "Metallic Silver",
        "rgb": "A5A9B4",
        "value": 80,
        "label": "Metallic Silver",
      },
      {
        "id": 81,
        "is_trans": false,
        "name": "Metallic Green",
        "rgb": "899B5F",
        "value": 81,
        "label": "Metallic Green",
      },
      {
        "id": 82,
        "is_trans": false,
        "name": "Metallic Gold",
        "rgb": "DBAC34",
        "value": 82,
        "label": "Metallic Gold",
      },
      {
        "id": 84,
        "is_trans": false,
        "name": "Medium Nougat",
        "rgb": "AA7D55",
        "value": 84,
        "label": "Medium Nougat",
      },
      {
        "id": 85,
        "is_trans": false,
        "name": "Dark Purple",
        "rgb": "3F3691",
        "value": 85,
        "label": "Dark Purple",
      },
      {
        "id": 86,
        "is_trans": false,
        "name": "Light Brown",
        "rgb": "7C503A",
        "value": 86,
        "label": "Light Brown",
      },
      {
        "id": 89,
        "is_trans": false,
        "name": "Royal Blue",
        "rgb": "4C61DB",
        "value": 89,
        "label": "Royal Blue",
      },
      {
        "id": 92,
        "is_trans": false,
        "name": "Nougat",
        "rgb": "D09168",
        "value": 92,
        "label": "Nougat",
      },
      {
        "id": 100,
        "is_trans": false,
        "name": "Light Salmon",
        "rgb": "FEBABD",
        "value": 100,
        "label": "Light Salmon",
      },
      {
        "id": 110,
        "is_trans": false,
        "name": "Violet",
        "rgb": "4354A3",
        "value": 110,
        "label": "Violet",
      },
      {
        "id": 112,
        "is_trans": false,
        "name": "Medium Bluish Violet",
        "rgb": "6874CA",
        "value": 112,
        "label": "Medium Bluish Violet",
      },
      {
        "id": 114,
        "is_trans": true,
        "name": "Glitter Trans-Dark Pink",
        "rgb": "DF6695",
        "value": 114,
        "label": "Glitter Trans-Dark Pink",
      },
      {
        "id": 115,
        "is_trans": false,
        "name": "Medium Lime",
        "rgb": "C7D23C",
        "value": 115,
        "label": "Medium Lime",
      },
      {
        "id": 117,
        "is_trans": true,
        "name": "Glitter Trans-Clear",
        "rgb": "FFFFFF",
        "value": 117,
        "label": "Glitter Trans-Clear",
      },
      {
        "id": 118,
        "is_trans": false,
        "name": "Aqua",
        "rgb": "B3D7D1",
        "value": 118,
        "label": "Aqua",
      },
      {
        "id": 120,
        "is_trans": false,
        "name": "Light Lime",
        "rgb": "D9E4A7",
        "value": 120,
        "label": "Light Lime",
      },
      {
        "id": 125,
        "is_trans": false,
        "name": "Light Orange",
        "rgb": "F9BA61",
        "value": 125,
        "label": "Light Orange",
      },
      {
        "id": 129,
        "is_trans": true,
        "name": "Glitter Trans-Purple",
        "rgb": "A5A5CB",
        "value": 129,
        "label": "Glitter Trans-Purple",
      },
      {
        "id": 132,
        "is_trans": false,
        "name": "Speckle Black-Silver",
        "rgb": "05131D",
        "value": 132,
        "label": "Speckle Black-Silver",
      },
      {
        "id": 133,
        "is_trans": false,
        "name": "Speckle Black-Gold",
        "rgb": "05131D",
        "value": 133,
        "label": "Speckle Black-Gold",
      },
      {
        "id": 134,
        "is_trans": false,
        "name": "Copper",
        "rgb": "AE7A59",
        "value": 134,
        "label": "Copper",
      },
      {
        "id": 135,
        "is_trans": false,
        "name": "Pearl Light Gray",
        "rgb": "9CA3A8",
        "value": 135,
        "label": "Pearl Light Gray",
      },
      {
        "id": 137,
        "is_trans": false,
        "name": "Pearl Sand Blue",
        "rgb": "7988A1",
        "value": 137,
        "label": "Pearl Sand Blue",
      },
      {
        "id": 142,
        "is_trans": false,
        "name": "Pearl Light Gold",
        "rgb": "DCBC81",
        "value": 142,
        "label": "Pearl Light Gold",
      },
      {
        "id": 143,
        "is_trans": true,
        "name": "Trans-Medium Blue",
        "rgb": "CFE2F7",
        "value": 143,
        "label": "Trans-Medium Blue",
      },
      {
        "id": 148,
        "is_trans": false,
        "name": "Pearl Dark Gray",
        "rgb": "575857",
        "value": 148,
        "label": "Pearl Dark Gray",
      },
      {
        "id": 150,
        "is_trans": false,
        "name": "Pearl Very Light Gray",
        "rgb": "ABADAC",
        "value": 150,
        "label": "Pearl Very Light Gray",
      },
      {
        "id": 151,
        "is_trans": false,
        "name": "Very Light Bluish Gray",
        "rgb": "E6E3E0",
        "value": 151,
        "label": "Very Light Bluish Gray",
      },
      {
        "id": 158,
        "is_trans": false,
        "name": "Yellowish Green",
        "rgb": "DFEEA5",
        "value": 158,
        "label": "Yellowish Green",
      },
      {
        "id": 178,
        "is_trans": false,
        "name": "Flat Dark Gold",
        "rgb": "B48455",
        "value": 178,
        "label": "Flat Dark Gold",
      },
      {
        "id": 179,
        "is_trans": false,
        "name": "Flat Silver",
        "rgb": "898788",
        "value": 179,
        "label": "Flat Silver",
      },
      {
        "id": 182,
        "is_trans": true,
        "name": "Trans-Orange",
        "rgb": "F08F1C",
        "value": 182,
        "label": "Trans-Orange",
      },
      {
        "id": 183,
        "is_trans": false,
        "name": "Pearl White",
        "rgb": "F2F3F2",
        "value": 183,
        "label": "Pearl White",
      },
      {
        "id": 191,
        "is_trans": false,
        "name": "Bright Light Orange",
        "rgb": "F8BB3D",
        "value": 191,
        "label": "Bright Light Orange",
      },
      {
        "id": 212,
        "is_trans": false,
        "name": "Bright Light Blue",
        "rgb": "9FC3E9",
        "value": 212,
        "label": "Bright Light Blue",
      },
      {
        "id": 216,
        "is_trans": false,
        "name": "Rust",
        "rgb": "B31004",
        "value": 216,
        "label": "Rust",
      },
      {
        "id": 226,
        "is_trans": false,
        "name": "Bright Light Yellow",
        "rgb": "FFF03A",
        "value": 226,
        "label": "Bright Light Yellow",
      },
      {
        "id": 230,
        "is_trans": true,
        "name": "Trans-Pink",
        "rgb": "E4ADC8",
        "value": 230,
        "label": "Trans-Pink",
      },
      {
        "id": 232,
        "is_trans": false,
        "name": "Sky Blue",
        "rgb": "7DBFDD",
        "value": 232,
        "label": "Sky Blue",
      },
      {
        "id": 236,
        "is_trans": true,
        "name": "Trans-Light Purple",
        "rgb": "96709F",
        "value": 236,
        "label": "Trans-Light Purple",
      },
      {
        "id": 272,
        "is_trans": false,
        "name": "Dark Blue",
        "rgb": "0A3463",
        "value": 272,
        "label": "Dark Blue",
      },
      {
        "id": 288,
        "is_trans": false,
        "name": "Dark Green",
        "rgb": "184632",
        "value": 288,
        "label": "Dark Green",
      },
      {
        "id": 294,
        "is_trans": true,
        "name": "Glow In Dark Trans",
        "rgb": "BDC6AD",
        "value": 294,
        "label": "Glow In Dark Trans",
      },
      {
        "id": 297,
        "is_trans": false,
        "name": "Pearl Gold",
        "rgb": "AA7F2E",
        "value": 297,
        "label": "Pearl Gold",
      },
      {
        "id": 308,
        "is_trans": false,
        "name": "Dark Brown",
        "rgb": "352100",
        "value": 308,
        "label": "Dark Brown",
      },
      {
        "id": 313,
        "is_trans": false,
        "name": "Maersk Blue",
        "rgb": "3592C3",
        "value": 313,
        "label": "Maersk Blue",
      },
      {
        "id": 320,
        "is_trans": false,
        "name": "Dark Red",
        "rgb": "720E0F",
        "value": 320,
        "label": "Dark Red",
      },
      {
        "id": 321,
        "is_trans": false,
        "name": "Dark Azure",
        "rgb": "078BC9",
        "value": 321,
        "label": "Dark Azure",
      },
      {
        "id": 322,
        "is_trans": false,
        "name": "Medium Azure",
        "rgb": "36AEBF",
        "value": 322,
        "label": "Medium Azure",
      },
      {
        "id": 323,
        "is_trans": false,
        "name": "Light Aqua",
        "rgb": "ADC3C0",
        "value": 323,
        "label": "Light Aqua",
      },
      {
        "id": 326,
        "is_trans": false,
        "name": "Olive Green",
        "rgb": "9B9A5A",
        "value": 326,
        "label": "Olive Green",
      },
      {
        "id": 334,
        "is_trans": false,
        "name": "Chrome Gold",
        "rgb": "BBA53D",
        "value": 334,
        "label": "Chrome Gold",
      },
      {
        "id": 335,
        "is_trans": false,
        "name": "Sand Red",
        "rgb": "D67572",
        "value": 335,
        "label": "Sand Red",
      },
      {
        "id": 351,
        "is_trans": false,
        "name": "Medium Dark Pink",
        "rgb": "F785B1",
        "value": 351,
        "label": "Medium Dark Pink",
      },
      {
        "id": 366,
        "is_trans": false,
        "name": "Earth Orange",
        "rgb": "FA9C1C",
        "value": 366,
        "label": "Earth Orange",
      },
      {
        "id": 373,
        "is_trans": false,
        "name": "Sand Purple",
        "rgb": "845E84",
        "value": 373,
        "label": "Sand Purple",
      },
      {
        "id": 378,
        "is_trans": false,
        "name": "Sand Green",
        "rgb": "A0BCAC",
        "value": 378,
        "label": "Sand Green",
      },
      {
        "id": 379,
        "is_trans": false,
        "name": "Sand Blue",
        "rgb": "6074A1",
        "value": 379,
        "label": "Sand Blue",
      },
      {
        "id": 383,
        "is_trans": false,
        "name": "Chrome Silver",
        "rgb": "E0E0E0",
        "value": 383,
        "label": "Chrome Silver",
      },
      {
        "id": 450,
        "is_trans": false,
        "name": "Fabuland Brown",
        "rgb": "B67B50",
        "value": 450,
        "label": "Fabuland Brown",
      },
      {
        "id": 462,
        "is_trans": false,
        "name": "Medium Orange",
        "rgb": "FFA70B",
        "value": 462,
        "label": "Medium Orange",
      },
      {
        "id": 484,
        "is_trans": false,
        "name": "Dark Orange",
        "rgb": "A95500",
        "value": 484,
        "label": "Dark Orange",
      },
      {
        "id": 503,
        "is_trans": false,
        "name": "Very Light Gray",
        "rgb": "E6E3DA",
        "value": 503,
        "label": "Very Light Gray",
      },
      {
        "id": 1000,
        "is_trans": false,
        "name": "Glow in Dark White",
        "rgb": "D9D9D9",
        "value": 1000,
        "label": "Glow in Dark White",
      },
      {
        "id": 1001,
        "is_trans": false,
        "name": "Medium Violet",
        "rgb": "9391E4",
        "value": 1001,
        "label": "Medium Violet",
      },
      {
        "id": 1002,
        "is_trans": true,
        "name": "Glitter Trans-Neon Green",
        "rgb": "C0F500",
        "value": 1002,
        "label": "Glitter Trans-Neon Green",
      },
      {
        "id": 1003,
        "is_trans": true,
        "name": "Glitter Trans-Light Blue",
        "rgb": "68BCC5",
        "value": 1003,
        "label": "Glitter Trans-Light Blue",
      },
      {
        "id": 1004,
        "is_trans": true,
        "name": "Trans-Flame Yellowish Orange",
        "rgb": "FCB76D",
        "value": 1004,
        "label": "Trans-Flame Yellowish Orange",
      },
      {
        "id": 1005,
        "is_trans": true,
        "name": "Trans-Fire Yellow",
        "rgb": "FBE890",
        "value": 1005,
        "label": "Trans-Fire Yellow",
      },
      {
        "id": 1006,
        "is_trans": true,
        "name": "Trans-Light Royal Blue",
        "rgb": "B4D4F7",
        "value": 1006,
        "label": "Trans-Light Royal Blue",
      },
      {
        "id": 1007,
        "is_trans": false,
        "name": "Reddish Lilac",
        "rgb": "8E5597",
        "value": 1007,
        "label": "Reddish Lilac",
      },
      {
        "id": 1008,
        "is_trans": false,
        "name": "Vintage Blue",
        "rgb": "039CBD",
        "value": 1008,
        "label": "Vintage Blue",
      },
      {
        "id": 1009,
        "is_trans": false,
        "name": "Vintage Green",
        "rgb": "1E601E",
        "value": 1009,
        "label": "Vintage Green",
      },
      {
        "id": 1010,
        "is_trans": false,
        "name": "Vintage Red",
        "rgb": "CA1F08",
        "value": 1010,
        "label": "Vintage Red",
      },
      {
        "id": 1011,
        "is_trans": false,
        "name": "Vintage Yellow",
        "rgb": "F3C305",
        "value": 1011,
        "label": "Vintage Yellow",
      },
      {
        "id": 1012,
        "is_trans": false,
        "name": "Fabuland Orange",
        "rgb": "EF9121",
        "value": 1012,
        "label": "Fabuland Orange",
      },
      {
        "id": 1013,
        "is_trans": false,
        "name": "Modulex White",
        "rgb": "F4F4F4",
        "value": 1013,
        "label": "Modulex White",
      },
      {
        "id": 1014,
        "is_trans": false,
        "name": "Modulex Light Bluish Gray",
        "rgb": "AfB5C7",
        "value": 1014,
        "label": "Modulex Light Bluish Gray",
      },
      {
        "id": 1015,
        "is_trans": false,
        "name": "Modulex Light Gray",
        "rgb": "9C9C9C",
        "value": 1015,
        "label": "Modulex Light Gray",
      },
      {
        "id": 1016,
        "is_trans": false,
        "name": "Modulex Charcoal Gray",
        "rgb": "595D60",
        "value": 1016,
        "label": "Modulex Charcoal Gray",
      },
      {
        "id": 1017,
        "is_trans": false,
        "name": "Modulex Tile Gray",
        "rgb": "6B5A5A",
        "value": 1017,
        "label": "Modulex Tile Gray",
      },
      {
        "id": 1018,
        "is_trans": false,
        "name": "Modulex Black",
        "rgb": "4D4C52",
        "value": 1018,
        "label": "Modulex Black",
      },
      {
        "id": 1019,
        "is_trans": false,
        "name": "Modulex Tile Brown",
        "rgb": "330000",
        "value": 1019,
        "label": "Modulex Tile Brown",
      },
      {
        "id": 1020,
        "is_trans": false,
        "name": "Modulex Terracotta",
        "rgb": "5C5030",
        "value": 1020,
        "label": "Modulex Terracotta",
      },
      {
        "id": 1021,
        "is_trans": false,
        "name": "Modulex Brown",
        "rgb": "907450",
        "value": 1021,
        "label": "Modulex Brown",
      },
      {
        "id": 1022,
        "is_trans": false,
        "name": "Modulex Buff",
        "rgb": "DEC69C",
        "value": 1022,
        "label": "Modulex Buff",
      },
      {
        "id": 1023,
        "is_trans": false,
        "name": "Modulex Red",
        "rgb": "B52C20",
        "value": 1023,
        "label": "Modulex Red",
      },
      {
        "id": 1024,
        "is_trans": false,
        "name": "Modulex Pink Red",
        "rgb": "F45C40",
        "value": 1024,
        "label": "Modulex Pink Red",
      },
      {
        "id": 1025,
        "is_trans": false,
        "name": "Modulex Orange",
        "rgb": "F47B30",
        "value": 1025,
        "label": "Modulex Orange",
      },
      {
        "id": 1026,
        "is_trans": false,
        "name": "Modulex Light Orange",
        "rgb": "F7AD63",
        "value": 1026,
        "label": "Modulex Light Orange",
      },
      {
        "id": 1027,
        "is_trans": false,
        "name": "Modulex Light Yellow",
        "rgb": "FFE371",
        "value": 1027,
        "label": "Modulex Light Yellow",
      },
      {
        "id": 1028,
        "is_trans": false,
        "name": "Modulex Ochre Yellow",
        "rgb": "FED557",
        "value": 1028,
        "label": "Modulex Ochre Yellow",
      },
      {
        "id": 1029,
        "is_trans": false,
        "name": "Modulex Lemon",
        "rgb": "BDC618",
        "value": 1029,
        "label": "Modulex Lemon",
      },
      {
        "id": 1030,
        "is_trans": false,
        "name": "Modulex Pastel Green",
        "rgb": "7DB538",
        "value": 1030,
        "label": "Modulex Pastel Green",
      },
      {
        "id": 1031,
        "is_trans": false,
        "name": "Modulex Olive Green",
        "rgb": "7C9051",
        "value": 1031,
        "label": "Modulex Olive Green",
      },
      {
        "id": 1032,
        "is_trans": false,
        "name": "Modulex Aqua Green",
        "rgb": "27867E",
        "value": 1032,
        "label": "Modulex Aqua Green",
      },
      {
        "id": 1033,
        "is_trans": false,
        "name": "Modulex Teal Blue",
        "rgb": "467083",
        "value": 1033,
        "label": "Modulex Teal Blue",
      },
      {
        "id": 1034,
        "is_trans": false,
        "name": "Modulex Tile Blue",
        "rgb": "0057A6",
        "value": 1034,
        "label": "Modulex Tile Blue",
      },
      {
        "id": 1035,
        "is_trans": false,
        "name": "Modulex Medium Blue",
        "rgb": "61AFFF",
        "value": 1035,
        "label": "Modulex Medium Blue",
      },
      {
        "id": 1036,
        "is_trans": false,
        "name": "Modulex Pastel Blue",
        "rgb": "68AECE",
        "value": 1036,
        "label": "Modulex Pastel Blue",
      },
      {
        "id": 1037,
        "is_trans": false,
        "name": "Modulex Violet",
        "rgb": "BD7D85",
        "value": 1037,
        "label": "Modulex Violet",
      },
      {
        "id": 1038,
        "is_trans": false,
        "name": "Modulex Pink",
        "rgb": "F785B1",
        "value": 1038,
        "label": "Modulex Pink",
      },
      {
        "id": 1039,
        "is_trans": false,
        "name": "Modulex Clear",
        "rgb": "FFFFFF",
        "value": 1039,
        "label": "Modulex Clear",
      },
      {
        "id": 1040,
        "is_trans": false,
        "name": "Modulex Foil Dark Gray",
        "rgb": "595D60",
        "value": 1040,
        "label": "Modulex Foil Dark Gray",
      },
      {
        "id": 1041,
        "is_trans": false,
        "name": "Modulex Foil Light Gray",
        "rgb": "9C9C9C",
        "value": 1041,
        "label": "Modulex Foil Light Gray",
      },
      {
        "id": 1042,
        "is_trans": false,
        "name": "Modulex Foil Dark Green",
        "rgb": "006400",
        "value": 1042,
        "label": "Modulex Foil Dark Green",
      },
      {
        "id": 1043,
        "is_trans": false,
        "name": "Modulex Foil Light Green",
        "rgb": "7DB538",
        "value": 1043,
        "label": "Modulex Foil Light Green",
      },
      {
        "id": 1044,
        "is_trans": false,
        "name": "Modulex Foil Dark Blue",
        "rgb": "0057A6",
        "value": 1044,
        "label": "Modulex Foil Dark Blue",
      },
      {
        "id": 1045,
        "is_trans": false,
        "name": "Modulex Foil Light Blue",
        "rgb": "68AECE",
        "value": 1045,
        "label": "Modulex Foil Light Blue",
      },
      {
        "id": 1046,
        "is_trans": false,
        "name": "Modulex Foil Violet",
        "rgb": "4B0082",
        "value": 1046,
        "label": "Modulex Foil Violet",
      },
      {
        "id": 1047,
        "is_trans": false,
        "name": "Modulex Foil Red",
        "rgb": "8B0000",
        "value": 1047,
        "label": "Modulex Foil Red",
      },
      {
        "id": 1048,
        "is_trans": false,
        "name": "Modulex Foil Yellow",
        "rgb": "FED557",
        "value": 1048,
        "label": "Modulex Foil Yellow",
      },
      {
        "id": 1049,
        "is_trans": false,
        "name": "Modulex Foil Orange",
        "rgb": "F7AD63",
        "value": 1049,
        "label": "Modulex Foil Orange",
      },
      {
        "id": 1050,
        "is_trans": false,
        "name": "Coral",
        "rgb": "FF698F",
        "value": 1050,
        "label": "Coral",
      },
      {
        "id": 1051,
        "is_trans": false,
        "name": "Pastel Blue",
        "rgb": "5AC4DA",
        "value": 1051,
        "label": "Pastel Blue",
      },
      {
        "id": 1052,
        "is_trans": true,
        "name": "Glitter Trans-Orange",
        "rgb": "F08F1C",
        "value": 1052,
        "label": "Glitter Trans-Orange",
      },
      {
        "id": 1053,
        "is_trans": true,
        "name": "Trans-Blue Opal",
        "rgb": "68BCC5",
        "value": 1053,
        "label": "Trans-Blue Opal",
      },
      {
        "id": 1054,
        "is_trans": true,
        "name": "Trans-Dark Pink Opal",
        "rgb": "CE1D9B",
        "value": 1054,
        "label": "Trans-Dark Pink Opal",
      },
      {
        "id": 1055,
        "is_trans": true,
        "name": "Trans-Clear Opal",
        "rgb": "FCFCFC",
        "value": 1055,
        "label": "Trans-Clear Opal",
      },
      {
        "id": 1056,
        "is_trans": true,
        "name": "Trans-Brown Opal",
        "rgb": "583927",
        "value": 1056,
        "label": "Trans-Brown Opal",
      },
      {
        "id": 1057,
        "is_trans": true,
        "name": "Trans-Light Bright Green",
        "rgb": "C9E788",
        "value": 1057,
        "label": "Trans-Light Bright Green",
      },
      {
        "id": 1058,
        "is_trans": true,
        "name": "Trans-Light Green",
        "rgb": "94E5AB",
        "value": 1058,
        "label": "Trans-Light Green",
      },
      {
        "id": 1059,
        "is_trans": true,
        "name": "Trans-Purple Opal",
        "rgb": "8320B7",
        "value": 1059,
        "label": "Trans-Purple Opal",
      },
      {
        "id": 1060,
        "is_trans": true,
        "name": "Trans-Green Opal",
        "rgb": "84B68D",
        "value": 1060,
        "label": "Trans-Green Opal",
      },
      {
        "id": 1061,
        "is_trans": true,
        "name": "Trans-Dark Blue Opal",
        "rgb": "0020A0",
        "value": 1061,
        "label": "Trans-Dark Blue Opal",
      },
      {
        "id": 1062,
        "is_trans": false,
        "name": "Vibrant Yellow",
        "rgb": "EBD800",
        "value": 1062,
        "label": "Vibrant Yellow",
      },
      {
        "id": 1063,
        "is_trans": false,
        "name": "Pearl Copper",
        "rgb": "B46A00",
        "value": 1063,
        "label": "Pearl Copper",
      },
      {
        "id": 1064,
        "is_trans": false,
        "name": "Fabuland Red",
        "rgb": "FF8014",
        "value": 1064,
        "label": "Fabuland Red",
      },
      {
        "id": 1065,
        "is_trans": false,
        "name": "Reddish Gold",
        "rgb": "AC8247",
        "value": 1065,
        "label": "Reddish Gold",
      },
      {
        "id": 1066,
        "is_trans": false,
        "name": "Curry",
        "rgb": "DD982E",
        "value": 1066,
        "label": "Curry",
      },
      {
        "id": 1067,
        "is_trans": false,
        "name": "Dark Nougat",
        "rgb": "AD6140",
        "value": 1067,
        "label": "Dark Nougat",
      },
      {
        "id": 1068,
        "is_trans": false,
        "name": "Bright Reddish Orange",
        "rgb": "EE5434",
        "value": 1068,
        "label": "Bright Reddish Orange",
      },
      {
        "id": 1069,
        "is_trans": false,
        "name": "Pearl Red",
        "rgb": "D60026",
        "value": 1069,
        "label": "Pearl Red",
      },
      {
        "id": 1070,
        "is_trans": false,
        "name": "Pearl Blue",
        "rgb": "0059A3",
        "value": 1070,
        "label": "Pearl Blue",
      },
      {
        "id": 1071,
        "is_trans": false,
        "name": "Pearl Green",
        "rgb": "008E3C",
        "value": 1071,
        "label": "Pearl Green",
      },
      {
        "id": 1072,
        "is_trans": false,
        "name": "Pearl Brown",
        "rgb": "57392C",
        "value": 1072,
        "label": "Pearl Brown",
      },
      {
        "id": 1073,
        "is_trans": false,
        "name": "Pearl Black",
        "rgb": "0A1327",
        "value": 1073,
        "label": "Pearl Black",
      },
      {
        "id": 1074,
        "is_trans": false,
        "name": "Duplo Blue",
        "rgb": "009ECE",
        "value": 1074,
        "label": "Duplo Blue",
      },
      {
        "id": 1075,
        "is_trans": false,
        "name": "Duplo Medium Blue",
        "rgb": "3E95B6",
        "value": 1075,
        "label": "Duplo Medium Blue",
      },
      {
        "id": 1076,
        "is_trans": false,
        "name": "Duplo Lime",
        "rgb": "FFF230",
        "value": 1076,
        "label": "Duplo Lime",
      },
      {
        "id": 1077,
        "is_trans": false,
        "name": "Fabuland Lime",
        "rgb": "78FC78",
        "value": 1077,
        "label": "Fabuland Lime",
      },
      {
        "id": 1078,
        "is_trans": false,
        "name": "Duplo Medium Green",
        "rgb": "468A5F",
        "value": 1078,
        "label": "Duplo Medium Green",
      },
      {
        "id": 1079,
        "is_trans": false,
        "name": "Duplo Light Green",
        "rgb": "60BA76",
        "value": 1079,
        "label": "Duplo Light Green",
      },
      {
        "id": 1080,
        "is_trans": false,
        "name": "Light Tan",
        "rgb": "F3C988",
        "value": 1080,
        "label": "Light Tan",
      },
      {
        "id": 1081,
        "is_trans": false,
        "name": "Rust Orange",
        "rgb": "872B17",
        "value": 1081,
        "label": "Rust Orange",
      },
      {
        "id": 1082,
        "is_trans": false,
        "name": "Clikits Pink",
        "rgb": "FE78B0",
        "value": 1082,
        "label": "Clikits Pink",
      },
      {
        "id": 1083,
        "is_trans": false,
        "name": "Two-tone Copper",
        "rgb": "945148",
        "value": 1083,
        "label": "Two-tone Copper",
      },
      {
        "id": 1084,
        "is_trans": false,
        "name": "Two-tone Gold",
        "rgb": "AB673A",
        "value": 1084,
        "label": "Two-tone Gold",
      },
      {
        "id": 1085,
        "is_trans": false,
        "name": "Two-tone Silver",
        "rgb": "737271",
        "value": 1085,
        "label": "Two-tone Silver",
      },
      {
        "id": 1086,
        "is_trans": false,
        "name": "Pearl Lime",
        "rgb": "6A7944",
        "value": 1086,
        "label": "Pearl Lime",
      },
      {
        "id": 1087,
        "is_trans": false,
        "name": "Duplo Pink",
        "rgb": "FF879C",
        "value": 1087,
        "label": "Duplo Pink",
      },
      {
        "id": 1088,
        "is_trans": false,
        "name": "Medium Brown",
        "rgb": "755945",
        "value": 1088,
        "label": "Medium Brown",
      },
      {
        "id": 1089,
        "is_trans": false,
        "name": "Warm Tan",
        "rgb": "CCA373",
        "value": 1089,
        "label": "Warm Tan",
      },
      {
        "id": 1090,
        "is_trans": false,
        "name": "Duplo Turquoise",
        "rgb": "3FB69E",
        "value": 1090,
        "label": "Duplo Turquoise",
      },
      {
        "id": 1091,
        "is_trans": false,
        "name": "Warm Yellowish Orange",
        "rgb": "FFCB78",
        "value": 1091,
        "label": "Warm Yellowish Orange",
      },
      {
        "id": 1092,
        "is_trans": false,
        "name": "Metallic Copper",
        "rgb": "764D3B",
        "value": 1092,
        "label": "Metallic Copper",
      },
      {
        "id": 1093,
        "is_trans": false,
        "name": "Light Lilac",
        "rgb": "9195CA",
        "value": 1093,
        "label": "Light Lilac",
      },
      {
        "id": 1094,
        "is_trans": false,
        "name": "Trans-Medium Purple",
        "rgb": "8D73B3",
        "value": 1094,
        "label": "Trans-Medium Purple",
      },
      {
        "id": 1095,
        "is_trans": true,
        "name": "Trans-Black",
        "rgb": "635F52",
        "value": 1095,
        "label": "Trans-Black",
      },
      {
        "id": 1096,
        "is_trans": true,
        "name": "Glitter Trans-Bright Green",
        "rgb": "D9E4A7",
        "value": 1096,
        "label": "Glitter Trans-Bright Green",
      },
      {
        "id": 1097,
        "is_trans": true,
        "name": "Glitter Trans-Medium Purple",
        "rgb": "8D73B3",
        "value": 1097,
        "label": "Glitter Trans-Medium Purple",
      },
      {
        "id": 1098,
        "is_trans": true,
        "name": "Glitter Trans-Green",
        "rgb": "84B68D",
        "value": 1098,
        "label": "Glitter Trans-Green",
      },
      {
        "id": 1099,
        "is_trans": true,
        "name": "Glitter Trans-Pink",
        "rgb": "E4ADC8",
        "value": 1099,
        "label": "Glitter Trans-Pink",
      },
      {
        "id": 1100,
        "is_trans": false,
        "name": "Clikits Yellow",
        "rgb": "FFCF0B",
        "value": 1100,
        "label": "Clikits Yellow",
      },
      {
        "id": 1101,
        "is_trans": false,
        "name": "Duplo Dark Purple",
        "rgb": "5F27AA",
        "value": 1101,
        "label": "Duplo Dark Purple",
      },
      {
        "id": 1102,
        "is_trans": true,
        "name": "Trans-Neon Red",
        "rgb": "FF0040",
        "value": 1102,
        "label": "Trans-Neon Red",
      },
      {
        "id": 1103,
        "is_trans": false,
        "name": "Pearl Titanium",
        "rgb": "3E3C39",
        "value": 1103,
        "label": "Pearl Titanium",
      },
      {
        "id": 1104,
        "is_trans": false,
        "name": "HO Aqua",
        "rgb": "B3D7D1",
        "value": 1104,
        "label": "HO Aqua",
      },
      {
        "id": 1105,
        "is_trans": false,
        "name": "HO Azure",
        "rgb": "1591cb",
        "value": 1105,
        "label": "HO Azure",
      },
      {
        "id": 1106,
        "is_trans": false,
        "name": "HO Blue-gray",
        "rgb": "354e5a",
        "value": 1106,
        "label": "HO Blue-gray",
      },
      {
        "id": 1107,
        "is_trans": false,
        "name": "HO Cyan",
        "rgb": "5b98b3",
        "value": 1107,
        "label": "HO Cyan",
      },
      {
        "id": 1108,
        "is_trans": false,
        "name": "HO Dark Aqua",
        "rgb": "a7dccf",
        "value": 1108,
        "label": "HO Dark Aqua",
      },
      {
        "id": 1109,
        "is_trans": false,
        "name": "HO Dark Blue",
        "rgb": "0A3463",
        "value": 1109,
        "label": "HO Dark Blue",
      },
      {
        "id": 1110,
        "is_trans": false,
        "name": "HO Dark Gray",
        "rgb": "6D6E5C",
        "value": 1110,
        "label": "HO Dark Gray",
      },
      {
        "id": 1111,
        "is_trans": false,
        "name": "HO Dark Green",
        "rgb": "184632",
        "value": 1111,
        "label": "HO Dark Green",
      },
      {
        "id": 1112,
        "is_trans": false,
        "name": "HO Dark Lime",
        "rgb": "b2b955",
        "value": 1112,
        "label": "HO Dark Lime",
      },
      {
        "id": 1113,
        "is_trans": false,
        "name": "HO Dark Red",
        "rgb": "631314",
        "value": 1113,
        "label": "HO Dark Red",
      },
      {
        "id": 1114,
        "is_trans": false,
        "name": "HO Dark Sand Green",
        "rgb": "627a62",
        "value": 1114,
        "label": "HO Dark Sand Green",
      },
      {
        "id": 1115,
        "is_trans": false,
        "name": "HO Dark Turquoise",
        "rgb": "10929d",
        "value": 1115,
        "label": "HO Dark Turquoise",
      },
      {
        "id": 1116,
        "is_trans": false,
        "name": "HO Earth Orange",
        "rgb": "bb771b",
        "value": 1116,
        "label": "HO Earth Orange",
      },
      {
        "id": 1117,
        "is_trans": false,
        "name": "HO Gold",
        "rgb": "b4a774",
        "value": 1117,
        "label": "HO Gold",
      },
      {
        "id": 1118,
        "is_trans": false,
        "name": "HO Light Aqua",
        "rgb": "a3d1c0",
        "value": 1118,
        "label": "HO Light Aqua",
      },
      {
        "id": 1119,
        "is_trans": false,
        "name": "HO Light Brown",
        "rgb": "965336",
        "value": 1119,
        "label": "HO Light Brown",
      },
      {
        "id": 1120,
        "is_trans": false,
        "name": "HO Light Gold",
        "rgb": "cdc298",
        "value": 1120,
        "label": "HO Light Gold",
      },
      {
        "id": 1121,
        "is_trans": false,
        "name": "HO Light Tan",
        "rgb": "f9f1c7",
        "value": 1121,
        "label": "HO Light Tan",
      },
      {
        "id": 1122,
        "is_trans": false,
        "name": "HO Light Yellow",
        "rgb": "f5fab7",
        "value": 1122,
        "label": "HO Light Yellow",
      },
      {
        "id": 1123,
        "is_trans": false,
        "name": "HO Medium Blue",
        "rgb": "7396c8",
        "value": 1123,
        "label": "HO Medium Blue",
      },
      {
        "id": 1124,
        "is_trans": false,
        "name": "HO Medium Red",
        "rgb": "c01111",
        "value": 1124,
        "label": "HO Medium Red",
      },
      {
        "id": 1125,
        "is_trans": false,
        "name": "HO Metallic Blue",
        "rgb": "0d4763",
        "value": 1125,
        "label": "HO Metallic Blue",
      },
      {
        "id": 1126,
        "is_trans": false,
        "name": "HO Metallic Dark Gray",
        "rgb": "5e5e5e",
        "value": 1126,
        "label": "HO Metallic Dark Gray",
      },
      {
        "id": 1127,
        "is_trans": false,
        "name": "HO Metallic Green",
        "rgb": "879867",
        "value": 1127,
        "label": "HO Metallic Green",
      },
      {
        "id": 1128,
        "is_trans": false,
        "name": "HO Metallic Sand Blue",
        "rgb": "5f7d8c",
        "value": 1128,
        "label": "HO Metallic Sand Blue",
      },
      {
        "id": 1129,
        "is_trans": false,
        "name": "HO Olive Green",
        "rgb": "9B9A5A",
        "value": 1129,
        "label": "HO Olive Green",
      },
      {
        "id": 1130,
        "is_trans": false,
        "name": "HO Rose",
        "rgb": "d06262",
        "value": 1130,
        "label": "HO Rose",
      },
      {
        "id": 1131,
        "is_trans": false,
        "name": "HO Sand Blue",
        "rgb": "6e8aa6",
        "value": 1131,
        "label": "HO Sand Blue",
      },
      {
        "id": 1132,
        "is_trans": false,
        "name": "HO Sand Green",
        "rgb": "A0BCAC",
        "value": 1132,
        "label": "HO Sand Green",
      },
      {
        "id": 1133,
        "is_trans": false,
        "name": "HO Tan",
        "rgb": "E4CD9E",
        "value": 1133,
        "label": "HO Tan",
      },
      {
        "id": 1134,
        "is_trans": false,
        "name": "HO Titanium",
        "rgb": "616161",
        "value": 1134,
        "label": "HO Titanium",
      },
      {
        "id": 1135,
        "is_trans": false,
        "name": "Metal",
        "rgb": "A5ADB4",
        "value": 1135,
        "label": "Metal",
      },
      {
        "id": 1136,
        "is_trans": false,
        "name": "Reddish Orange",
        "rgb": "CA4C0B",
        "value": 1136,
        "label": "Reddish Orange",
      },
      {
        "id": 1137,
        "is_trans": false,
        "name": "Sienna Brown",
        "rgb": "915C3C",
        "value": 1137,
        "label": "Sienna Brown",
      },
      {
        "id": 1138,
        "is_trans": false,
        "name": "Umber Brown",
        "rgb": "5E3F33",
        "value": 1138,
        "label": "Umber Brown",
      }
  ]

//   for (var color of colors) {
//     console.log("{\n" +
//           '  "id": ' + color.id+",\n" +
//           '  "is_trans": ' + color.is_trans+",\n" + 
//           '  "name": "' + color.name+'",\n' + 
//           '  "rgb": "' + color.rgb+'",\n' + 
//           '  "value": ' + color.id+',\n' + 
//           '  "label": "' + color.name+'",\n' + 
//           '},')
//   }

export default colors